### ISSUE TITLE
Is there any document about Run this CLM3.5 ？

### ISSUE THREAD

**Issue by andrewsoong** [HPSCTerrSys/CLM3.5#1]
**Is there any documentation on how to run this modified CLM3.5 model? I see some additions to the NCAR/CLM 3.5 model. Is there an introduction? In addition, how to make OASIS3 data for the region of interest (netcdf format) ?
Can this modified CLM3.5 model be run independently？
Thanks！**

**Comment by kvrigor** [comment]
Hi @andrewsoong,

Our modified CLM3.5 is developed under the context of the [Terrestrial Systems Modelling Platform (TSMP)](https://github.com/HPSCTerrSys/TSMP). This means that this model is suitable only for partially- or fully coupled simulations within the TSMP framework.

You can find the original CLM3.5 documentation [here](https://web.archive.org/web/20220701121954/https://www.cgd.ucar.edu/tss/clm/distribution/clm3.5/index.html). CLM3.5 is quite old and I would suggest to instead use the latest model [CTSM](https://escomp.github.io/ctsm-docs/versions/master/html/index.html).

**Comment by andrewsoong** [comment]
> Hi @andrewsoong,
> 
> Our modified CLM3.5 is developed under the context of the [Terrestrial Systems Modelling Platform (TSMP)](https://github.com/HPSCTerrSys/TSMP). This means that this model is suitable only for partially- or fully coupled simulations within the TSMP framework.
> 
> You can find the original CLM3.5 documentation [here](https://web.archive.org/web/20220701121954/https://www.cgd.ucar.edu/tss/clm/distribution/clm3.5/index.html). CLM3.5 is quite old and I would suggest to instead use the latest model [CTSM](https://escomp.github.io/ctsm-docs/versions/master/html/index.html).

Thank you! CTSM is the newest model, but My computer can't work with this new model. The off-line CLM3.5 is suitable for me with good performance in hydrology. Thanks again！
